# Generated by Django 2.1.7 on 2019-03-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date scanned')),
                ('url', models.TextField()),
                ('found', models.IntegerField()),
            ],
        ),
    ]
