# Generated by Django 2.1.7 on 2019-03-17 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('vac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(verbose_name='date scanned')),
                ('id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('area', models.IntegerField()),
                ('salary_from', models.IntegerField(default=None)),
                ('salary_to', models.IntegerField(default=None)),
                ('requirement', models.TextField(default=None)),
                ('responsibility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workstats.Vacancies', to_field='id')),
                ('date_time', models.DateTimeField(verbose_name='date scanned')),
                ('created_date_time', models.DateTimeField(default=None, verbose_name='created date')),
                ('description', models.TextField(default=None)),
                ('experience', models.TextField(default=None)),
                ('employer_name', models.TextField(default=None)),
                ('employer_id', models.IntegerField(default=None)),
                ('close_date_time', models.DateTimeField(default=None, verbose_name='date of close')),
                ('archive_date_time', models.DateTimeField(default=None, verbose_name='date of archive')),
            ],
        ),
    ]
