# Generated by Django 2.1.7 on 2019-03-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstats', '0002_vacancies_vacanciesdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacanciesdetails',
            old_name='id',
            new_name='vacancie',
        ),
    ]
