# Generated by Django 2.1.7 on 2019-03-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstats', '0003_auto_20190317_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='vac_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
