# Generated by Django 2.1.7 on 2019-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstats', '0004_auto_20190317_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='date_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date scanned'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirement',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='responsibility',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_from',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
