# Generated by Django 2.1.7 on 2019-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstats', '0005_auto_20190317_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='archive_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date of archive'),
        ),
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='close_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date of close'),
        ),
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='created_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='employer_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='employer_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacanciesdetails',
            name='experience',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
